apiVersion: v1
kind: Pod
metadata:
  name: read-only-fs
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    securityContext:
      # read-only fs explicitly defined
      readOnlyRootFilesystem: false
