# Privileged Pod (K01.01) & Resource Limits (K0.04)
apiVersion: v1
kind: Pod
metadata:
  name: dodgy-pod
  namespace: default
  labels:
    app: my-dodgy-app
    environment: testing
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    #securityContext explicitly defined
    securityContext:
       privileged: true

# Read-only FileSystem Pod (K01.02)
apiVersion: v1
kind: Pod
metadata:
  name: read-only-fs
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    securityContext:
      #read-only fs explicitly defined
      readOnlyRootFilesystem: true

# Run as Root User (K01.03)
apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
spec:
  containers:
  - name: root-container
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0  # This specifies that the container runs as root
